/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package qubexplorer.ui;

/**
 *
 * @author Victor
 */
public class RuleCount2 extends javax.swing.JPanel {

    /**
     * Creates new form RuleCount2
     */
    public RuleCount2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jXHyperlink2 = new org.jdesktop.swingx.JXHyperlink();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jXHyperlink3 = new org.jdesktop.swingx.JXHyperlink();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jXHyperlink4 = new org.jdesktop.swingx.JXHyperlink();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jXHyperlink5 = new org.jdesktop.swingx.JXHyperlink();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jXHyperlink6 = new org.jdesktop.swingx.JXHyperlink();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.setColumns(10);
        jTextField1.setFont(jTextField1.getFont().deriveFont(jTextField1.getFont().getSize()+5f));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText(org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jTextField1.text")); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jPanel2.add(jTextField1);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jButton1.text")); // NOI18N
        jPanel2.add(jButton1);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jButton7.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton7, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jButton7.text")); // NOI18N
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel13.add(jButton7);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+5f));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jLabel1.text")); // NOI18N
        jPanel13.add(jLabel1);

        jPanel1.add(jPanel13, java.awt.BorderLayout.CENTER);

        add(jPanel1);

        jPanel3.setBackground(new java.awt.Color(238, 238, 238));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setOpaque(false);

        jTextField2.setEditable(false);
        jTextField2.setColumns(10);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText(org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jTextField2.text")); // NOI18N
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        jPanel4.add(jTextField2);

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jButton2.text")); // NOI18N
        jPanel4.add(jButton2);

        jPanel3.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jXHyperlink2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        org.openide.awt.Mnemonics.setLocalizedText(jXHyperlink2, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jXHyperlink2.text")); // NOI18N
        jPanel3.add(jXHyperlink2, java.awt.BorderLayout.CENTER);

        add(jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jTextField3.setEditable(false);
        jTextField3.setColumns(10);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText(org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jTextField3.text")); // NOI18N
        jTextField3.setBorder(null);
        jTextField3.setOpaque(false);
        jPanel6.add(jTextField3);

        org.openide.awt.Mnemonics.setLocalizedText(jButton3, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jButton3.text")); // NOI18N
        jPanel6.add(jButton3);

        jPanel5.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jXHyperlink3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        org.openide.awt.Mnemonics.setLocalizedText(jXHyperlink3, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jXHyperlink3.text")); // NOI18N
        jPanel5.add(jXHyperlink3, java.awt.BorderLayout.CENTER);

        add(jPanel5);

        jPanel7.setBackground(new java.awt.Color(238, 238, 238));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setOpaque(false);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(240, 240, 240));
        jTextField4.setColumns(10);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setText(org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jTextField4.text")); // NOI18N
        jTextField4.setBorder(null);
        jTextField4.setOpaque(false);
        jPanel8.add(jTextField4);

        org.openide.awt.Mnemonics.setLocalizedText(jButton4, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jButton4.text")); // NOI18N
        jPanel8.add(jButton4);

        jPanel7.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jXHyperlink4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        org.openide.awt.Mnemonics.setLocalizedText(jXHyperlink4, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jXHyperlink4.text")); // NOI18N
        jPanel7.add(jXHyperlink4, java.awt.BorderLayout.CENTER);

        add(jPanel7);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jTextField5.setEditable(false);
        jTextField5.setColumns(10);
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setText(org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jTextField5.text")); // NOI18N
        jTextField5.setBorder(null);
        jTextField5.setOpaque(false);
        jPanel10.add(jTextField5);

        org.openide.awt.Mnemonics.setLocalizedText(jButton5, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jButton5.text")); // NOI18N
        jPanel10.add(jButton5);

        jPanel9.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jXHyperlink5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        org.openide.awt.Mnemonics.setLocalizedText(jXHyperlink5, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jXHyperlink5.text")); // NOI18N
        jPanel9.add(jXHyperlink5, java.awt.BorderLayout.CENTER);

        add(jPanel9);

        jPanel11.setBackground(new java.awt.Color(238, 238, 238));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setOpaque(false);

        jTextField6.setEditable(false);
        jTextField6.setColumns(10);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setText(org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jTextField6.text")); // NOI18N
        jTextField6.setBorder(null);
        jTextField6.setOpaque(false);
        jPanel12.add(jTextField6);

        org.openide.awt.Mnemonics.setLocalizedText(jButton6, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jButton6.text")); // NOI18N
        jPanel12.add(jButton6);

        jPanel11.add(jPanel12, java.awt.BorderLayout.LINE_END);

        jXHyperlink6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        org.openide.awt.Mnemonics.setLocalizedText(jXHyperlink6, org.openide.util.NbBundle.getMessage(RuleCount2.class, "RuleCount2.jXHyperlink6.text")); // NOI18N
        jPanel11.add(jXHyperlink6, java.awt.BorderLayout.CENTER);

        add(jPanel11);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink2;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink3;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink4;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink5;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink6;
    // End of variables declaration//GEN-END:variables
}
