package qubexplorer.ui;

import java.awt.Frame;
import java.util.List;
import java.util.concurrent.ExecutionException;
import javax.swing.SwingWorker;
import org.netbeans.api.progress.ProgressHandle;
import org.netbeans.api.progress.ProgressHandleFactory;
import org.netbeans.api.project.Project;
import org.openide.util.Exceptions;
import org.openide.util.NbPreferences;
import org.openide.windows.WindowManager;
import org.sonar.wsclient.base.HttpException;
import org.sonar.wsclient.issue.Issue;
import qubexplorer.Authentication;
import qubexplorer.SonarQube;
import qubexplorer.ui.options.SonarQubePanel;

/**
 *
 * @author Victor
 */
public class SonarQubeDialog extends javax.swing.JDialog {
    private Project project;

    /**
     * Creates new form SonarQubeDialog
     */
    public SonarQubeDialog(java.awt.Frame parent, boolean modal, Project project) {
        super(parent, modal);
        this.project=project;
        initComponents();
        getRootPane().setDefaultButton(jButton1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboSeverity = new javax.swing.JComboBox();

        setTitle(org.openide.util.NbBundle.getMessage(SonarQubeDialog.class, "SonarQubeDialog.title")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(SonarQubeDialog.class, "SonarQubeDialog.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(SonarQubeDialog.class, "SonarQubeDialog.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SonarQubeDialog.class, "SonarQubeDialog.jLabel1.text")); // NOI18N

        comboSeverity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Any", "Blocker", "Critical", "Major", "Minor", "Info" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 134, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboSeverity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SonarTopComponent sonarTopComponent = (SonarTopComponent) WindowManager.getDefault().findTopComponent("SonarTopComponent");
        String key = SonarQube.toResource(project);
        setVisible(false);
        final String severity=(String) comboSeverity.getSelectedItem();
        final String address=NbPreferences.forModule(SonarQubePanel.class).get("address", "http://localhost:9000");
        SwingWorker<List<Issue>, Void> worker=new IssuesWorker(address, key, severity, sonarTopComponent);
        worker.execute();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SonarQubeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SonarQubeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SonarQubeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SonarQubeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SonarQubeDialog dialog = new SonarQubeDialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboSeverity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private class IssuesWorker extends SwingWorker<List<Issue>, Void> {

        private final String address;
        private final String key;
        private final String severity;
        private final Authentication auth;
        private final SonarTopComponent sonarTopComponent;
        private ProgressHandle handle;

        public IssuesWorker(String address, String key, String severity, SonarTopComponent sonarTopComponent) {
            this.address = address;
            this.key = key;
            this.severity = severity;
            this.sonarTopComponent = sonarTopComponent;
            auth=null;
            init();
        }
        
        public IssuesWorker(Authentication auth, String address, String key, String severity, SonarTopComponent sonarTopComponent) {
            this.address = address;
            this.key = key;
            this.severity = severity;
            this.sonarTopComponent = sonarTopComponent;
            this.auth=auth;
            init();
        }
        
        private void init() {
            handle = ProgressHandleFactory.createHandle("Sonar");
            handle.switchToIndeterminate();
            handle.start();
        }

        @Override
        protected List<Issue> doInBackground() throws Exception {
            return new SonarQube(address).getIssues(auth, key, severity);
        }

        @Override
        protected void done() {
            try {
                sonarTopComponent.setIssues(get().toArray(new Issue[0]));
                sonarTopComponent.open();
                sonarTopComponent.requestVisible();
                sonarTopComponent.setProject(project);
            } catch (InterruptedException ex) {
                Exceptions.printStackTrace(ex);
            } catch(ExecutionException ex){
                if(ex.getCause() instanceof HttpException) {
                    if(((HttpException)ex.getCause()).status() == 401) {
                        handle.finish();
                        Authentication authentication = AuthDialog.showAuthDialog((Frame)SonarQubeDialog.this.getOwner());
                        if(authentication != null) {
                            IssuesWorker worker = new IssuesWorker(authentication, address, key, severity, sonarTopComponent);
                            worker.execute();
                        }
                    }
                }else{
                    Exceptions.printStackTrace(ex);
                }
            }finally{
                handle.finish();
            }
        }
    }
}
